{
	"version": 1624906489,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/imagens-sheet0.png",
		"images/imagens-sheet1.png",
		"images/imagens-sheet2.png",
		"images/palavra1.png",
		"images/roleta_palavras-sheet0.png",
		"images/botao_girar1-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/roleta_atividades-sheet0.png",
		"images/andre-sheet0.png",
		"images/fundo-sheet0.png",
		"images/fundo_roleta-sheet0.png",
		"images/fundo_roleta-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/botao_play-sheet0.png",
		"images/holofote-sheet0.png",
		"images/marcacao-sheet0.png",
		"images/botao_screenshot-sheet0.png",
		"images/botao_screenshot-sheet1.png",
		"images/canvas.png",
		"images/sprite-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/envelope-sheet0.png",
		"images/envelope-sheet1.png",
		"images/particles.png",
		"images/botao_ferramentas-sheet0.png",
		"images/bt_musicafundo-sheet0.png",
		"images/bt_musicafundo-sheet1.png",
		"images/bt_somgeral-sheet0.png",
		"images/bt_somgeral-sheet1.png",
		"images/bt_volume-sheet0.png",
		"images/bt_volume-sheet1.png",
		"media/roleta girando.ogg",
		"media/selected.ogg",
		"media/palmas_win.ogg",
		"media/background.ogg",
		"media/1 - gire a roleta - atividade.ogg",
		"media/2 - vai rodando.ogg",
		"media/3 - a atividade sorteada foi.ogg",
		"media/3-1 formacao de frases.ogg",
		"media/3-2 separacao de silabas.ogg",
		"media/3-3 concordancia.ogg",
		"media/3-4 silaba tonica.ogg",
		"media/4 - muito bem roleta animal.ogg",
		"media/5 - girar novamente.ogg",
		"media/6 - escolha envelope.ogg",
		"media/7 - forme frase.ogg",
		"media/a1 - rato.ogg",
		"media/a10 - zebra.ogg",
		"media/a11 - girafa.ogg",
		"media/a12 - elefante.ogg",
		"media/a2 - minhoca.ogg",
		"media/a3 - leao.ogg",
		"media/a4 - gato.ogg",
		"media/a5 - tartaruga.ogg",
		"media/a6 - cachorro.ogg",
		"media/a7 - papagaio.ogg",
		"media/a8 - formiga.ogg",
		"media/a9 - cavalo.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"palavras.json",
		"animate.min.css"
	]
}